/* File generated by the BNF Converter (bnfc 2.9.6.3). */

//C++ Abstract Syntax Implementation.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"

/********************   Conf    ********************/
Conf::Conf(ListSection *p1)
{
  listsection_ = p1;

}

Conf::Conf(const Conf & other)
{
  listsection_ = other.listsection_->clone();

}

Conf &Conf::operator=(const Conf & other)
{
  Conf tmp(other);
  swap(tmp);
  return *this;
}

void Conf::swap(Conf & other)
{
  std::swap(listsection_, other.listsection_);

}

Conf::~Conf()
{
  delete(listsection_);

}

void Conf::accept(Visitor *v)
{
  v->visitConf(this);
}

Conf *Conf::clone() const
{
  return new Conf(*this);
}



/********************   Sect    ********************/
Sect::Sect(Ident p1, ListField *p2)
{
  ident_ = p1;
  listfield_ = p2;

}

Sect::Sect(const Sect & other)
{
  ident_ = other.ident_;
  listfield_ = other.listfield_->clone();

}

Sect &Sect::operator=(const Sect & other)
{
  Sect tmp(other);
  swap(tmp);
  return *this;
}

void Sect::swap(Sect & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listfield_, other.listfield_);

}

Sect::~Sect()
{
  delete(listfield_);

}

void Sect::accept(Visitor *v)
{
  v->visitSect(this);
}

Sect *Sect::clone() const
{
  return new Sect(*this);
}



/********************   Fld    ********************/
Fld::Fld(Ident p1, Value *p2)
{
  ident_ = p1;
  value_ = p2;

}

Fld::Fld(const Fld & other)
{
  ident_ = other.ident_;
  value_ = other.value_->clone();

}

Fld &Fld::operator=(const Fld & other)
{
  Fld tmp(other);
  swap(tmp);
  return *this;
}

void Fld::swap(Fld & other)
{
  std::swap(ident_, other.ident_);
  std::swap(value_, other.value_);

}

Fld::~Fld()
{
  delete(value_);

}

void Fld::accept(Visitor *v)
{
  v->visitFld(this);
}

Fld *Fld::clone() const
{
  return new Fld(*this);
}



/********************   VInt    ********************/
VInt::VInt(Integer p1)
{
  integer_ = p1;

}

VInt::VInt(const VInt & other)
{
  integer_ = other.integer_;

}

VInt &VInt::operator=(const VInt & other)
{
  VInt tmp(other);
  swap(tmp);
  return *this;
}

void VInt::swap(VInt & other)
{
  std::swap(integer_, other.integer_);

}

VInt::~VInt()
{

}

void VInt::accept(Visitor *v)
{
  v->visitVInt(this);
}

VInt *VInt::clone() const
{
  return new VInt(*this);
}



/********************   VBool    ********************/
VBool::VBool(Boolean *p1)
{
  boolean_ = p1;

}

VBool::VBool(const VBool & other)
{
  boolean_ = other.boolean_->clone();

}

VBool &VBool::operator=(const VBool & other)
{
  VBool tmp(other);
  swap(tmp);
  return *this;
}

void VBool::swap(VBool & other)
{
  std::swap(boolean_, other.boolean_);

}

VBool::~VBool()
{
  delete(boolean_);

}

void VBool::accept(Visitor *v)
{
  v->visitVBool(this);
}

VBool *VBool::clone() const
{
  return new VBool(*this);
}



/********************   VStr    ********************/
VStr::VStr(String p1)
{
  string_ = p1;

}

VStr::VStr(const VStr & other)
{
  string_ = other.string_;

}

VStr &VStr::operator=(const VStr & other)
{
  VStr tmp(other);
  swap(tmp);
  return *this;
}

void VStr::swap(VStr & other)
{
  std::swap(string_, other.string_);

}

VStr::~VStr()
{

}

void VStr::accept(Visitor *v)
{
  v->visitVStr(this);
}

VStr *VStr::clone() const
{
  return new VStr(*this);
}



/********************   VRef    ********************/
VRef::VRef(Ref *p1)
{
  ref_ = p1;

}

VRef::VRef(const VRef & other)
{
  ref_ = other.ref_->clone();

}

VRef &VRef::operator=(const VRef & other)
{
  VRef tmp(other);
  swap(tmp);
  return *this;
}

void VRef::swap(VRef & other)
{
  std::swap(ref_, other.ref_);

}

VRef::~VRef()
{
  delete(ref_);

}

void VRef::accept(Visitor *v)
{
  v->visitVRef(this);
}

VRef *VRef::clone() const
{
  return new VRef(*this);
}



/********************   RefLocal    ********************/
RefLocal::RefLocal(Ident p1)
{
  ident_ = p1;

}

RefLocal::RefLocal(const RefLocal & other)
{
  ident_ = other.ident_;

}

RefLocal &RefLocal::operator=(const RefLocal & other)
{
  RefLocal tmp(other);
  swap(tmp);
  return *this;
}

void RefLocal::swap(RefLocal & other)
{
  std::swap(ident_, other.ident_);

}

RefLocal::~RefLocal()
{

}

void RefLocal::accept(Visitor *v)
{
  v->visitRefLocal(this);
}

RefLocal *RefLocal::clone() const
{
  return new RefLocal(*this);
}



/********************   RefQual    ********************/
RefQual::RefQual(Ident p1, Ident p2)
{
  ident_1 = p1;
  ident_2 = p2;

}

RefQual::RefQual(const RefQual & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;

}

RefQual &RefQual::operator=(const RefQual & other)
{
  RefQual tmp(other);
  swap(tmp);
  return *this;
}

void RefQual::swap(RefQual & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);

}

RefQual::~RefQual()
{

}

void RefQual::accept(Visitor *v)
{
  v->visitRefQual(this);
}

RefQual *RefQual::clone() const
{
  return new RefQual(*this);
}



/********************   BTrue    ********************/
BTrue::BTrue()
{

}

BTrue::BTrue(const BTrue & other)
{

}

BTrue &BTrue::operator=(const BTrue & other)
{
  BTrue tmp(other);
  swap(tmp);
  return *this;
}

void BTrue::swap(BTrue & other)
{

}

BTrue::~BTrue()
{

}

void BTrue::accept(Visitor *v)
{
  v->visitBTrue(this);
}

BTrue *BTrue::clone() const
{
  return new BTrue(*this);
}



/********************   BFalse    ********************/
BFalse::BFalse()
{

}

BFalse::BFalse(const BFalse & other)
{

}

BFalse &BFalse::operator=(const BFalse & other)
{
  BFalse tmp(other);
  swap(tmp);
  return *this;
}

void BFalse::swap(BFalse & other)
{

}

BFalse::~BFalse()
{

}

void BFalse::accept(Visitor *v)
{
  v->visitBFalse(this);
}

BFalse *BFalse::clone() const
{
  return new BFalse(*this);
}




/********************   ListSection    ********************/

void ListSection::accept(Visitor *v)
{
  v->visitListSection(this);
}

ListSection *ListSection::clone() const
{
  return new ListSection(*this);
}

ListSection* consListSection(Section* x, ListSection* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListField    ********************/

void ListField::accept(Visitor *v)
{
  v->visitListField(this);
}

ListField *ListField::clone() const
{
  return new ListField(*this);
}

ListField* consListField(Field* x, ListField* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}





