/* File generated by the BNF Converter (bnfc 2.9.6.3). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitConfig(Config *p) {} //abstract class

void PrintAbsyn::visitConf(Conf *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListSection(p->listsection_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSection(Section *p) {} //abstract class

void PrintAbsyn::visitSect(Sect *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  render("section");
  render("name");
  render('=');
  visitIdent(p->ident_);
  render('>');
  _i_ = 0; visitListField(p->listfield_);
  render("</");
  render("section");
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitField(Field *p) {} //abstract class

void PrintAbsyn::visitFld(Fld *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  render("field");
  render("name");
  render('=');
  visitIdent(p->ident_);
  render('>');
  _i_ = 0; p->value_->accept(this);
  render("</");
  render("field");
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitValue(Value *p) {} //abstract class

void PrintAbsyn::visitVInt(VInt *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVBool(VBool *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->boolean_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVStr(VStr *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitString(p->string_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVRef(VRef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->ref_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRef(Ref *p) {} //abstract class

void PrintAbsyn::visitRefLocal(RefLocal *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('$');
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRefQual(RefQual *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('$');
  visitIdent(p->ident_1);
  render('.');
  visitIdent(p->ident_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBoolean(Boolean *p) {} //abstract class

void PrintAbsyn::visitBTrue(BTrue *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("true");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBFalse(BFalse *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("false");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListSection(ListSection *listsection)
{
  iterListSection(listsection->begin(), listsection->end());
}

void PrintAbsyn::iterListSection(ListSection::const_iterator i, ListSection::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListSection(i+1, j);
  }
}

void PrintAbsyn::visitListField(ListField *listfield)
{
  iterListField(listfield->begin(), listfield->end());
}

void PrintAbsyn::iterListField(ListField::const_iterator i, ListField::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListField(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
  bufAppend(' ');
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitConfig(Config *p) {} //abstract class

void ShowAbsyn::visitConf(Conf *p)
{
  bufAppend('(');
  bufAppend("Conf");
  bufAppend(' ');
  bufAppend('[');
  if (p->listsection_)  p->listsection_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitSection(Section *p) {} //abstract class

void ShowAbsyn::visitSect(Sect *p)
{
  bufAppend('(');
  bufAppend("Sect");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listfield_)  p->listfield_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitField(Field *p) {} //abstract class

void ShowAbsyn::visitFld(Fld *p)
{
  bufAppend('(');
  bufAppend("Fld");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitValue(Value *p) {} //abstract class

void ShowAbsyn::visitVInt(VInt *p)
{
  bufAppend('(');
  bufAppend("VInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitVBool(VBool *p)
{
  bufAppend('(');
  bufAppend("VBool");
  bufAppend(' ');
  bufAppend('[');
  if (p->boolean_)  p->boolean_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVStr(VStr *p)
{
  bufAppend('(');
  bufAppend("VStr");
  bufAppend(' ');
  visitString(p->string_);
  bufAppend(')');
}
void ShowAbsyn::visitVRef(VRef *p)
{
  bufAppend('(');
  bufAppend("VRef");
  bufAppend(' ');
  bufAppend('[');
  if (p->ref_)  p->ref_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitRef(Ref *p) {} //abstract class

void ShowAbsyn::visitRefLocal(RefLocal *p)
{
  bufAppend('(');
  bufAppend("RefLocal");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitRefQual(RefQual *p)
{
  bufAppend('(');
  bufAppend("RefQual");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(')');
}
void ShowAbsyn::visitBoolean(Boolean *p) {} //abstract class

void ShowAbsyn::visitBTrue(BTrue *p)
{
  bufAppend("BTrue");
}
void ShowAbsyn::visitBFalse(BFalse *p)
{
  bufAppend("BFalse");
}
void ShowAbsyn::visitListSection(ListSection *listsection)
{
  for (ListSection::const_iterator i = listsection->begin() ; i != listsection->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listsection->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListField(ListField *listfield)
{
  for (ListField::const_iterator i = listfield->begin() ; i != listfield->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfield->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


