# commento
# commento
<section name=nomesez1>
<field name=var1>3</field>
<field name=var2>"non dire gatto"</field>
# commento
<field name=var3>$var1</field>
</section>
<section name=nomesez2>
# commento
<field name=miao>true</field>
<field name=var1>false</field>
</section>
<section name=nomesez3>
<field name=miao>$nomesez1.var3</field>
<field name=var1>false</field>
</section>

