/* File generated by the BNF Converter (bnfc 2.9.6.3). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitConfig(Config *t) {} //abstract class
void Skeleton::visitSection(Section *t) {} //abstract class
void Skeleton::visitField(Field *t) {} //abstract class
void Skeleton::visitValue(Value *t) {} //abstract class
void Skeleton::visitRef(Ref *t) {} //abstract class
void Skeleton::visitBoolean(Boolean *t) {} //abstract class

void Skeleton::visitConf(Conf *conf)
{
  /* Code For Conf Goes Here */

  if (conf->listsection_) conf->listsection_->accept(this);

}

void Skeleton::visitSect(Sect *sect)
{
  /* Code For Sect Goes Here */

  visitIdent(sect->ident_);
  if (sect->listfield_) sect->listfield_->accept(this);

}

void Skeleton::visitFld(Fld *fld)
{
  /* Code For Fld Goes Here */

  visitIdent(fld->ident_);
  if (fld->value_) fld->value_->accept(this);

}

void Skeleton::visitVInt(VInt *v_int)
{
  /* Code For VInt Goes Here */

  visitInteger(v_int->integer_);

}

void Skeleton::visitVBool(VBool *v_bool)
{
  /* Code For VBool Goes Here */

  if (v_bool->boolean_) v_bool->boolean_->accept(this);

}

void Skeleton::visitVStr(VStr *v_str)
{
  /* Code For VStr Goes Here */

  visitString(v_str->string_);

}

void Skeleton::visitVRef(VRef *v_ref)
{
  /* Code For VRef Goes Here */

  if (v_ref->ref_) v_ref->ref_->accept(this);

}

void Skeleton::visitRefLocal(RefLocal *ref_local)
{
  /* Code For RefLocal Goes Here */

  visitIdent(ref_local->ident_);

}

void Skeleton::visitRefQual(RefQual *ref_qual)
{
  /* Code For RefQual Goes Here */

  visitIdent(ref_qual->ident_1);
  visitIdent(ref_qual->ident_2);

}

void Skeleton::visitBTrue(BTrue *b_true)
{
  /* Code For BTrue Goes Here */


}

void Skeleton::visitBFalse(BFalse *b_false)
{
  /* Code For BFalse Goes Here */


}


void Skeleton::visitListSection(ListSection *list_section)
{
  for (ListSection::iterator i = list_section->begin() ; i != list_section->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListField(ListField *list_field)
{
  for (ListField::iterator i = list_field->begin() ; i != list_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



