-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Linguaggio.

module AbsLinguaggio where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type Program = Program' BNFC'Position
data Program' a = Prog a [TopDecl' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type TopDecl = TopDecl' BNFC'Position
data TopDecl' a
    = DVar a Ident (Type' a)
    | DVarInit a Ident (Type' a) (Exp' a)
    | DProc a Ident [Param' a] (Type' a) (Block' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Param = Param' BNFC'Position
data Param' a = Par a (Intent' a) Ident (Type' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Intent = Intent' BNFC'Position
data Intent' a = IIn a | IRef a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Type = Type' BNFC'Position
data Type' a
    = TInt a
    | TBool a
    | TReal a
    | TChar a
    | TStr a
    | TVoid a
    | TArr a Integer Integer (Type' a)
    | TPtr a (Type' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Block = Block' BNFC'Position
data Block' a = BBlock a [Stmt' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Stmt = Stmt' BNFC'Position
data Stmt' a
    = SBlock a (Block' a)
    | SAssign a (Exp' a) (Exp' a)
    | SCall a Ident [Exp' a]
    | SReturn a (Exp' a)
    | SReturnV a
    | SDecl a (TopDecl' a)
    | SIf a (Exp' a) (Block' a)
    | SIfElse a (Exp' a) (Block' a) (Block' a)
    | SWhile a (Exp' a) (Block' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Exp = Exp' BNFC'Position
data Exp' a
    = EOr a (Exp' a) (Exp' a)
    | EAnd a (Exp' a) (Exp' a)
    | EEq a (Exp' a) (Exp' a)
    | ENeq a (Exp' a) (Exp' a)
    | ELt a (Exp' a) (Exp' a)
    | ELe a (Exp' a) (Exp' a)
    | EGt a (Exp' a) (Exp' a)
    | EGe a (Exp' a) (Exp' a)
    | EAdd a (Exp' a) (Exp' a)
    | ESub a (Exp' a) (Exp' a)
    | EMul a (Exp' a) (Exp' a)
    | EDiv a (Exp' a) (Exp' a)
    | ENeg a (Exp' a)
    | ENot a (Exp' a)
    | EDeref a (Exp' a)
    | EAddr a (Exp' a)
    | EIdx a (Exp' a) (Exp' a)
    | ECall a Ident [Exp' a]
    | EVar a Ident
    | EInt a Integer
    | EReal a Double
    | EChar a Char
    | EStr a String
    | ETrue a
    | EFalse a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    Prog p _ -> p

instance HasPosition TopDecl where
  hasPosition = \case
    DVar p _ _ -> p
    DVarInit p _ _ _ -> p
    DProc p _ _ _ _ -> p

instance HasPosition Param where
  hasPosition = \case
    Par p _ _ _ -> p

instance HasPosition Intent where
  hasPosition = \case
    IIn p -> p
    IRef p -> p

instance HasPosition Type where
  hasPosition = \case
    TInt p -> p
    TBool p -> p
    TReal p -> p
    TChar p -> p
    TStr p -> p
    TVoid p -> p
    TArr p _ _ _ -> p
    TPtr p _ -> p

instance HasPosition Block where
  hasPosition = \case
    BBlock p _ -> p

instance HasPosition Stmt where
  hasPosition = \case
    SBlock p _ -> p
    SAssign p _ _ -> p
    SCall p _ _ -> p
    SReturn p _ -> p
    SReturnV p -> p
    SDecl p _ -> p
    SIf p _ _ -> p
    SIfElse p _ _ _ -> p
    SWhile p _ _ -> p

instance HasPosition Exp where
  hasPosition = \case
    EOr p _ _ -> p
    EAnd p _ _ -> p
    EEq p _ _ -> p
    ENeq p _ _ -> p
    ELt p _ _ -> p
    ELe p _ _ -> p
    EGt p _ _ -> p
    EGe p _ _ -> p
    EAdd p _ _ -> p
    ESub p _ _ -> p
    EMul p _ _ -> p
    EDiv p _ _ -> p
    ENeg p _ -> p
    ENot p _ -> p
    EDeref p _ -> p
    EAddr p _ -> p
    EIdx p _ _ -> p
    ECall p _ _ -> p
    EVar p _ -> p
    EInt p _ -> p
    EReal p _ -> p
    EChar p _ -> p
    EStr p _ -> p
    ETrue p -> p
    EFalse p -> p

