-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Linguaggio.

module AbsLinguaggio where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Prog [TopDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TopDecl
    = DVar Ident Type
    | DVarInit Ident Type Exp
    | DProc Ident [Param] Type Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Param = Par Intent Ident Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Intent = IIn | IRef
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = TInt
    | TBool
    | TReal
    | TChar
    | TStr
    | TVoid
    | TArr Integer Integer Type
    | TPtr Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Block = BBlock [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
    = SBlock Block
    | SAssign Exp Exp
    | SCall Ident [Exp]
    | SReturn Exp
    | SReturnV
    | SDecl TopDecl
    | SIf Exp Block
    | SIfElse Exp Block Block
    | SWhile Exp Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EOr Exp Exp
    | EAnd Exp Exp
    | EEq Exp Exp
    | ENeq Exp Exp
    | ELt Exp Exp
    | ELe Exp Exp
    | EGt Exp Exp
    | EGe Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | ENeg Exp
    | ENot Exp
    | EDeref Exp
    | EAddr Exp
    | EIdx Exp Exp
    | ECall Ident [Exp]
    | EVar Ident
    | EInt Integer
    | EReal Double
    | EChar Char
    | EStr String
    | ETrue
    | EFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

