{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintLinguaggio.
--   Generated by the BNF converter.

module PrintLinguaggio where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsLinguaggio

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLinguaggio.Ident where
  prt _ (AbsLinguaggio.Ident i) = doc $ showString i

instance Print (AbsLinguaggio.Program' a) where
  prt i = \case
    AbsLinguaggio.Prog _ topdecls -> prPrec i 0 (concatD [prt 0 topdecls])

instance Print (AbsLinguaggio.TopDecl' a) where
  prt i = \case
    AbsLinguaggio.DVar _ id_ type_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString ":"), prt 0 type_, doc (showString ";")])
    AbsLinguaggio.DVarInit _ id_ type_ exp -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString ":"), prt 0 type_, doc (showString "="), prt 0 exp, doc (showString ";")])
    AbsLinguaggio.DProc _ id_ params type_ block -> prPrec i 0 (concatD [doc (showString "proc"), prt 0 id_, doc (showString "("), prt 0 params, doc (showString ")"), doc (showString ":"), prt 0 type_, prt 0 block])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsLinguaggio.TopDecl' a] where
  prt = prtList

instance Print (AbsLinguaggio.Param' a) where
  prt i = \case
    AbsLinguaggio.Par _ intent id_ type_ -> prPrec i 0 (concatD [prt 0 intent, prt 0 id_, doc (showString ":"), prt 0 type_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsLinguaggio.Param' a] where
  prt = prtList

instance Print (AbsLinguaggio.Intent' a) where
  prt i = \case
    AbsLinguaggio.IIn _ -> prPrec i 0 (concatD [])
    AbsLinguaggio.IRef _ -> prPrec i 0 (concatD [doc (showString "ref")])

instance Print (AbsLinguaggio.Type' a) where
  prt i = \case
    AbsLinguaggio.TInt _ -> prPrec i 0 (concatD [doc (showString "int")])
    AbsLinguaggio.TBool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsLinguaggio.TReal _ -> prPrec i 0 (concatD [doc (showString "real")])
    AbsLinguaggio.TChar _ -> prPrec i 0 (concatD [doc (showString "char")])
    AbsLinguaggio.TStr _ -> prPrec i 0 (concatD [doc (showString "string")])
    AbsLinguaggio.TVoid _ -> prPrec i 0 (concatD [doc (showString "void")])
    AbsLinguaggio.TArr _ n1 n2 type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 n1, doc (showString ".."), prt 0 n2, doc (showString "]"), prt 0 type_])
    AbsLinguaggio.TPtr _ type_ -> prPrec i 0 (concatD [doc (showString "c_ptr"), doc (showString "("), prt 0 type_, doc (showString ")")])

instance Print (AbsLinguaggio.Block' a) where
  prt i = \case
    AbsLinguaggio.BBlock _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsLinguaggio.Stmt' a] where
  prt = prtList

instance Print (AbsLinguaggio.Stmt' a) where
  prt i = \case
    AbsLinguaggio.SBlock _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsLinguaggio.SAssign _ exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "="), prt 0 exp2, doc (showString ";")])
    AbsLinguaggio.SCall _ id_ exps -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")"), doc (showString ";")])
    AbsLinguaggio.SReturn _ exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    AbsLinguaggio.SReturnV _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsLinguaggio.SDecl _ topdecl -> prPrec i 0 (concatD [prt 0 topdecl])
    AbsLinguaggio.SIf _ exp block -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, prt 0 block])
    AbsLinguaggio.SIfElse _ exp block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 exp, prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsLinguaggio.SWhile _ exp block -> prPrec i 0 (concatD [doc (showString "while"), prt 0 exp, prt 0 block])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsLinguaggio.Exp' a] where
  prt = prtList

instance Print (AbsLinguaggio.Exp' a) where
  prt i = \case
    AbsLinguaggio.EOr _ exp1 exp2 -> prPrec i 0 (concatD [prt 0 exp1, doc (showString "||"), prt 1 exp2])
    AbsLinguaggio.EAnd _ exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "&&"), prt 2 exp2])
    AbsLinguaggio.EEq _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "=="), prt 3 exp2])
    AbsLinguaggio.ENeq _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "!="), prt 3 exp2])
    AbsLinguaggio.ELt _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "<"), prt 3 exp2])
    AbsLinguaggio.ELe _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "<="), prt 3 exp2])
    AbsLinguaggio.EGt _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString ">"), prt 3 exp2])
    AbsLinguaggio.EGe _ exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString ">="), prt 3 exp2])
    AbsLinguaggio.EAdd _ exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "+"), prt 4 exp2])
    AbsLinguaggio.ESub _ exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "-"), prt 4 exp2])
    AbsLinguaggio.EMul _ exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "*"), prt 5 exp2])
    AbsLinguaggio.EDiv _ exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "/"), prt 5 exp2])
    AbsLinguaggio.ENeg _ exp -> prPrec i 5 (concatD [doc (showString "-"), prt 5 exp])
    AbsLinguaggio.ENot _ exp -> prPrec i 5 (concatD [doc (showString "!"), prt 5 exp])
    AbsLinguaggio.EDeref _ exp -> prPrec i 5 (concatD [doc (showString "*"), prt 5 exp])
    AbsLinguaggio.EAddr _ exp -> prPrec i 5 (concatD [doc (showString "c_ptrTo"), doc (showString "("), prt 0 exp, doc (showString ")")])
    AbsLinguaggio.EIdx _ exp1 exp2 -> prPrec i 6 (concatD [prt 6 exp1, doc (showString "["), prt 0 exp2, doc (showString "]")])
    AbsLinguaggio.ECall _ id_ exps -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsLinguaggio.EVar _ id_ -> prPrec i 7 (concatD [prt 0 id_])
    AbsLinguaggio.EInt _ n -> prPrec i 7 (concatD [prt 0 n])
    AbsLinguaggio.EReal _ d -> prPrec i 7 (concatD [prt 0 d])
    AbsLinguaggio.EChar _ c -> prPrec i 7 (concatD [prt 0 c])
    AbsLinguaggio.EStr _ str -> prPrec i 7 (concatD [prt 0 str])
    AbsLinguaggio.ETrue _ -> prPrec i 7 (concatD [doc (showString "true")])
    AbsLinguaggio.EFalse _ -> prPrec i 7 (concatD [doc (showString "false")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

