-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLinguaggio where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLinguaggio

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsLinguaggio.Ident -> Result
transIdent x = case x of
  AbsLinguaggio.Ident string -> failure x

transProgram :: AbsLinguaggio.Program -> Result
transProgram x = case x of
  AbsLinguaggio.Prog topdecls -> failure x

transTopDecl :: AbsLinguaggio.TopDecl -> Result
transTopDecl x = case x of
  AbsLinguaggio.DVar ident type_ -> failure x
  AbsLinguaggio.DVarInit ident type_ exp -> failure x
  AbsLinguaggio.DProc ident params type_ block -> failure x

transParam :: AbsLinguaggio.Param -> Result
transParam x = case x of
  AbsLinguaggio.Par intent ident type_ -> failure x

transIntent :: AbsLinguaggio.Intent -> Result
transIntent x = case x of
  AbsLinguaggio.IIn -> failure x
  AbsLinguaggio.IRef -> failure x

transType :: AbsLinguaggio.Type -> Result
transType x = case x of
  AbsLinguaggio.TInt -> failure x
  AbsLinguaggio.TBool -> failure x
  AbsLinguaggio.TReal -> failure x
  AbsLinguaggio.TChar -> failure x
  AbsLinguaggio.TStr -> failure x
  AbsLinguaggio.TVoid -> failure x
  AbsLinguaggio.TArr integer1 integer2 type_ -> failure x
  AbsLinguaggio.TPtr type_ -> failure x

transBlock :: AbsLinguaggio.Block -> Result
transBlock x = case x of
  AbsLinguaggio.BBlock stmts -> failure x

transStmt :: AbsLinguaggio.Stmt -> Result
transStmt x = case x of
  AbsLinguaggio.SBlock block -> failure x
  AbsLinguaggio.SAssign exp1 exp2 -> failure x
  AbsLinguaggio.SCall ident exps -> failure x
  AbsLinguaggio.SReturn exp -> failure x
  AbsLinguaggio.SReturnV -> failure x
  AbsLinguaggio.SDecl topdecl -> failure x
  AbsLinguaggio.SIf exp block -> failure x
  AbsLinguaggio.SIfElse exp block1 block2 -> failure x
  AbsLinguaggio.SWhile exp block -> failure x

transExp :: AbsLinguaggio.Exp -> Result
transExp x = case x of
  AbsLinguaggio.EOr exp1 exp2 -> failure x
  AbsLinguaggio.EAnd exp1 exp2 -> failure x
  AbsLinguaggio.EEq exp1 exp2 -> failure x
  AbsLinguaggio.ENeq exp1 exp2 -> failure x
  AbsLinguaggio.ELt exp1 exp2 -> failure x
  AbsLinguaggio.ELe exp1 exp2 -> failure x
  AbsLinguaggio.EGt exp1 exp2 -> failure x
  AbsLinguaggio.EGe exp1 exp2 -> failure x
  AbsLinguaggio.EAdd exp1 exp2 -> failure x
  AbsLinguaggio.ESub exp1 exp2 -> failure x
  AbsLinguaggio.EMul exp1 exp2 -> failure x
  AbsLinguaggio.EDiv exp1 exp2 -> failure x
  AbsLinguaggio.ENeg exp -> failure x
  AbsLinguaggio.ENot exp -> failure x
  AbsLinguaggio.EDeref exp -> failure x
  AbsLinguaggio.EAddr exp -> failure x
  AbsLinguaggio.EIdx exp1 exp2 -> failure x
  AbsLinguaggio.ECall ident exps -> failure x
  AbsLinguaggio.EVar ident -> failure x
  AbsLinguaggio.EInt integer -> failure x
  AbsLinguaggio.EReal double -> failure x
  AbsLinguaggio.EChar char -> failure x
  AbsLinguaggio.EStr string -> failure x
  AbsLinguaggio.ETrue -> failure x
  AbsLinguaggio.EFalse -> failure x
