-- This Happy file was machine-generated by the BNF converter
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
module ParLinguaggio
  ( happyError
  , myLexer
  , pProgram
  ) where

import Prelude

import qualified AbsLinguaggio
import LexLinguaggio

}

%name pProgram_internal Program
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '!' { PT _ (TS _ 1) }
  '!=' { PT _ (TS _ 2) }
  '&&' { PT _ (TS _ 3) }
  '(' { PT _ (TS _ 4) }
  ')' { PT _ (TS _ 5) }
  '*' { PT _ (TS _ 6) }
  '+' { PT _ (TS _ 7) }
  ',' { PT _ (TS _ 8) }
  '-' { PT _ (TS _ 9) }
  '..' { PT _ (TS _ 10) }
  '/' { PT _ (TS _ 11) }
  ':' { PT _ (TS _ 12) }
  ';' { PT _ (TS _ 13) }
  '<' { PT _ (TS _ 14) }
  '<=' { PT _ (TS _ 15) }
  '=' { PT _ (TS _ 16) }
  '==' { PT _ (TS _ 17) }
  '>' { PT _ (TS _ 18) }
  '>=' { PT _ (TS _ 19) }
  '[' { PT _ (TS _ 20) }
  ']' { PT _ (TS _ 21) }
  'bool' { PT _ (TS _ 22) }
  'c_ptr' { PT _ (TS _ 23) }
  'c_ptrTo' { PT _ (TS _ 24) }
  'char' { PT _ (TS _ 25) }
  'else' { PT _ (TS _ 26) }
  'false' { PT _ (TS _ 27) }
  'if' { PT _ (TS _ 28) }
  'int' { PT _ (TS _ 29) }
  'proc' { PT _ (TS _ 30) }
  'real' { PT _ (TS _ 31) }
  'ref' { PT _ (TS _ 32) }
  'return' { PT _ (TS _ 33) }
  'string' { PT _ (TS _ 34) }
  'true' { PT _ (TS _ 35) }
  'var' { PT _ (TS _ 36) }
  'void' { PT _ (TS _ 37) }
  'while' { PT _ (TS _ 38) }
  '{' { PT _ (TS _ 39) }
  '||' { PT _ (TS _ 40) }
  '}' { PT _ (TS _ 41) }
  L_Ident  { PT _ (TV _) }
  L_charac { PT _ (TC _) }
  L_doubl  { PT _ (TD _) }
  L_integ  { PT _ (TI _) }
  L_quoted { PT _ (TL _) }

%%

Ident :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Ident) }
Ident  : L_Ident { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.Ident (tokenText $1)) }

Char    :: { (AbsLinguaggio.BNFC'Position, Char) }
Char     : L_charac { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), (read (tokenText $1)) :: Char) }

Double  :: { (AbsLinguaggio.BNFC'Position, Double) }
Double   : L_doubl  { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), (read (tokenText $1)) :: Double) }

Integer :: { (AbsLinguaggio.BNFC'Position, Integer) }
Integer  : L_integ  { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), (read (tokenText $1)) :: Integer) }

String  :: { (AbsLinguaggio.BNFC'Position, String) }
String   : L_quoted { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), ((\(PT _ (TL s)) -> s) $1)) }

Program :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Program) }
Program : ListTopDecl { (fst $1, AbsLinguaggio.Prog (fst $1) (snd $1)) }

TopDecl :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.TopDecl) }
TopDecl : 'var' Ident ':' Type ';' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.DVar (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4)) }
        | 'var' Ident ':' Type '=' Exp ';' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.DVarInit (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $6)) }
        | 'proc' Ident '(' ListParam ')' ':' Type Block { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.DProc (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $7) (snd $8)) }

ListTopDecl :: { (AbsLinguaggio.BNFC'Position, [AbsLinguaggio.TopDecl]) }
ListTopDecl : {- empty -} { (AbsLinguaggio.BNFC'NoPosition, []) }
            | TopDecl ListTopDecl { (fst $1, (:) (snd $1) (snd $2)) }

Param :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Param) }
Param : Intent Ident ':' Type { (fst $1, AbsLinguaggio.Par (fst $1) (snd $1) (snd $2) (snd $4)) }

ListParam :: { (AbsLinguaggio.BNFC'Position, [AbsLinguaggio.Param]) }
ListParam : {- empty -} { (AbsLinguaggio.BNFC'NoPosition, []) }
          | Param { (fst $1, (:[]) (snd $1)) }
          | Param ',' ListParam { (fst $1, (:) (snd $1) (snd $3)) }

Intent :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Intent) }
Intent : {- empty -} { (AbsLinguaggio.BNFC'NoPosition, AbsLinguaggio.IIn AbsLinguaggio.BNFC'NoPosition) }
       | 'ref' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.IRef (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }

Type :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Type) }
Type : 'int' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TInt (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'bool' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TBool (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'real' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TReal (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'char' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TChar (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'string' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TStr (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'void' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TVoid (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | '[' Integer '..' Integer ']' Type { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TArr (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $4) (snd $6)) }
     | 'c_ptr' '(' Type ')' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.TPtr (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $3)) }

Block :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Block) }
Block : '{' ListStmt '}' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.BBlock (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2)) }

ListStmt :: { (AbsLinguaggio.BNFC'Position, [AbsLinguaggio.Stmt]) }
ListStmt : {- empty -} { (AbsLinguaggio.BNFC'NoPosition, []) }
         | Stmt ListStmt { (fst $1, (:) (snd $1) (snd $2)) }

Stmt :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Stmt) }
Stmt : Block { (fst $1, AbsLinguaggio.SBlock (fst $1) (snd $1)) }
     | Exp '=' Exp ';' { (fst $1, AbsLinguaggio.SAssign (fst $1) (snd $1) (snd $3)) }
     | Ident '(' ListExp ')' ';' { (fst $1, AbsLinguaggio.SCall (fst $1) (snd $1) (snd $3)) }
     | 'return' Exp ';' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.SReturn (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2)) }
     | 'return' ';' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.SReturnV (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | TopDecl { (fst $1, AbsLinguaggio.SDecl (fst $1) (snd $1)) }
     | 'if' Exp Block { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.SIf (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $3)) }
     | 'if' Exp Block 'else' Block { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.SIfElse (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $3) (snd $5)) }
     | 'while' Exp Block { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.SWhile (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2) (snd $3)) }

ListExp :: { (AbsLinguaggio.BNFC'Position, [AbsLinguaggio.Exp]) }
ListExp : {- empty -} { (AbsLinguaggio.BNFC'NoPosition, []) }
        | Exp { (fst $1, (:[]) (snd $1)) }
        | Exp ',' ListExp { (fst $1, (:) (snd $1) (snd $3)) }

Exp :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp : Exp '||' Exp1 { (fst $1, AbsLinguaggio.EOr (fst $1) (snd $1) (snd $3)) }
    | Exp1 { (fst $1, (snd $1)) }

Exp1 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp1 : Exp1 '&&' Exp2 { (fst $1, AbsLinguaggio.EAnd (fst $1) (snd $1) (snd $3)) }
     | Exp2 { (fst $1, (snd $1)) }

Exp2 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp2 : Exp3 '==' Exp3 { (fst $1, AbsLinguaggio.EEq (fst $1) (snd $1) (snd $3)) }
     | Exp3 '!=' Exp3 { (fst $1, AbsLinguaggio.ENeq (fst $1) (snd $1) (snd $3)) }
     | Exp3 '<' Exp3 { (fst $1, AbsLinguaggio.ELt (fst $1) (snd $1) (snd $3)) }
     | Exp3 '<=' Exp3 { (fst $1, AbsLinguaggio.ELe (fst $1) (snd $1) (snd $3)) }
     | Exp3 '>' Exp3 { (fst $1, AbsLinguaggio.EGt (fst $1) (snd $1) (snd $3)) }
     | Exp3 '>=' Exp3 { (fst $1, AbsLinguaggio.EGe (fst $1) (snd $1) (snd $3)) }
     | Exp3 { (fst $1, (snd $1)) }

Exp3 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp3 : Exp3 '+' Exp4 { (fst $1, AbsLinguaggio.EAdd (fst $1) (snd $1) (snd $3)) }
     | Exp3 '-' Exp4 { (fst $1, AbsLinguaggio.ESub (fst $1) (snd $1) (snd $3)) }
     | Exp4 { (fst $1, (snd $1)) }

Exp4 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp4 : Exp4 '*' Exp5 { (fst $1, AbsLinguaggio.EMul (fst $1) (snd $1) (snd $3)) }
     | Exp4 '/' Exp5 { (fst $1, AbsLinguaggio.EDiv (fst $1) (snd $1) (snd $3)) }
     | Exp5 { (fst $1, (snd $1)) }

Exp5 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp5 : '-' Exp5 { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.ENeg (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2)) }
     | '!' Exp5 { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.ENot (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2)) }
     | '*' Exp5 { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.EDeref (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $2)) }
     | 'c_ptrTo' '(' Exp ')' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.EAddr (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1)) (snd $3)) }
     | Exp6 { (fst $1, (snd $1)) }

Exp6 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp6 : Exp6 '[' Exp ']' { (fst $1, AbsLinguaggio.EIdx (fst $1) (snd $1) (snd $3)) }
     | Ident '(' ListExp ')' { (fst $1, AbsLinguaggio.ECall (fst $1) (snd $1) (snd $3)) }
     | Exp7 { (fst $1, (snd $1)) }

Exp7 :: { (AbsLinguaggio.BNFC'Position, AbsLinguaggio.Exp) }
Exp7 : Ident { (fst $1, AbsLinguaggio.EVar (fst $1) (snd $1)) }
     | Integer { (fst $1, AbsLinguaggio.EInt (fst $1) (snd $1)) }
     | Double { (fst $1, AbsLinguaggio.EReal (fst $1) (snd $1)) }
     | Char { (fst $1, AbsLinguaggio.EChar (fst $1) (snd $1)) }
     | String { (fst $1, AbsLinguaggio.EStr (fst $1) (snd $1)) }
     | 'true' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.ETrue (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | 'false' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), AbsLinguaggio.EFalse (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1))) }
     | '(' Exp ')' { (uncurry AbsLinguaggio.BNFC'Position (tokenLineCol $1), (snd $2)) }
{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: String -> [Token]
myLexer = tokens

-- Entrypoints

pProgram :: [Token] -> Err AbsLinguaggio.Program
pProgram = fmap snd . pProgram_internal
}

