-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLinguaggio where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLinguaggio

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsLinguaggio.Ident -> Result
transIdent x = case x of
  AbsLinguaggio.Ident string -> failure x

transProgram :: Show a => AbsLinguaggio.Program' a -> Result
transProgram x = case x of
  AbsLinguaggio.Prog _ topdecls -> failure x

transTopDecl :: Show a => AbsLinguaggio.TopDecl' a -> Result
transTopDecl x = case x of
  AbsLinguaggio.DVar _ ident type_ -> failure x
  AbsLinguaggio.DVarInit _ ident type_ exp -> failure x
  AbsLinguaggio.DProc _ ident params type_ block -> failure x

transParam :: Show a => AbsLinguaggio.Param' a -> Result
transParam x = case x of
  AbsLinguaggio.Par _ intent ident type_ -> failure x

transIntent :: Show a => AbsLinguaggio.Intent' a -> Result
transIntent x = case x of
  AbsLinguaggio.IIn _ -> failure x
  AbsLinguaggio.IRef _ -> failure x

transType :: Show a => AbsLinguaggio.Type' a -> Result
transType x = case x of
  AbsLinguaggio.TInt _ -> failure x
  AbsLinguaggio.TBool _ -> failure x
  AbsLinguaggio.TReal _ -> failure x
  AbsLinguaggio.TChar _ -> failure x
  AbsLinguaggio.TStr _ -> failure x
  AbsLinguaggio.TVoid _ -> failure x
  AbsLinguaggio.TArr _ integer1 integer2 type_ -> failure x
  AbsLinguaggio.TPtr _ type_ -> failure x

transBlock :: Show a => AbsLinguaggio.Block' a -> Result
transBlock x = case x of
  AbsLinguaggio.BBlock _ stmts -> failure x

transStmt :: Show a => AbsLinguaggio.Stmt' a -> Result
transStmt x = case x of
  AbsLinguaggio.SBlock _ block -> failure x
  AbsLinguaggio.SAssign _ exp1 exp2 -> failure x
  AbsLinguaggio.SCall _ ident exps -> failure x
  AbsLinguaggio.SReturn _ exp -> failure x
  AbsLinguaggio.SReturnV _ -> failure x
  AbsLinguaggio.SDecl _ topdecl -> failure x
  AbsLinguaggio.SIf _ exp block -> failure x
  AbsLinguaggio.SIfElse _ exp block1 block2 -> failure x
  AbsLinguaggio.SWhile _ exp block -> failure x

transExp :: Show a => AbsLinguaggio.Exp' a -> Result
transExp x = case x of
  AbsLinguaggio.EOr _ exp1 exp2 -> failure x
  AbsLinguaggio.EAnd _ exp1 exp2 -> failure x
  AbsLinguaggio.EEq _ exp1 exp2 -> failure x
  AbsLinguaggio.ENeq _ exp1 exp2 -> failure x
  AbsLinguaggio.ELt _ exp1 exp2 -> failure x
  AbsLinguaggio.ELe _ exp1 exp2 -> failure x
  AbsLinguaggio.EGt _ exp1 exp2 -> failure x
  AbsLinguaggio.EGe _ exp1 exp2 -> failure x
  AbsLinguaggio.EAdd _ exp1 exp2 -> failure x
  AbsLinguaggio.ESub _ exp1 exp2 -> failure x
  AbsLinguaggio.EMul _ exp1 exp2 -> failure x
  AbsLinguaggio.EDiv _ exp1 exp2 -> failure x
  AbsLinguaggio.ENeg _ exp -> failure x
  AbsLinguaggio.ENot _ exp -> failure x
  AbsLinguaggio.EDeref _ exp -> failure x
  AbsLinguaggio.EAddr _ exp -> failure x
  AbsLinguaggio.EIdx _ exp1 exp2 -> failure x
  AbsLinguaggio.ECall _ ident exps -> failure x
  AbsLinguaggio.EVar _ ident -> failure x
  AbsLinguaggio.EInt _ integer -> failure x
  AbsLinguaggio.EReal _ double -> failure x
  AbsLinguaggio.EChar _ char -> failure x
  AbsLinguaggio.EStr _ string -> failure x
  AbsLinguaggio.ETrue _ -> failure x
  AbsLinguaggio.EFalse _ -> failure x
